server:
  port: 8189
  servlet:
    context-path: /happy
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/happy
    username: postgres
    password: postgres
  jpa:
    show-sql: true
